version: '3'

services:
    homeassistant:
        container_name: hass
        image: homeassistant/home-assistant:stable
        restart: unless-stopped
        volumes:
          - ./hassio-config:/config
        ports:
            - 8123:8123
            - 8300:8300
            - 51827:51827
        # network_mode: host
        environment:
          - TZ=${TZ}
