version: '3'

services:
    homeassistant:
        container_name: hass
        image: homeassistant/home-assistant:stable
        restart: unless-stopped
        volumes:
          - ./hassio-config:/config
        ports:
            - 8123:8123
        environment:
          - TZ=${TZ}
